from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MATRIX_DIR = PROJECT_ROOT / "matrixs"
HOMOGRAPHY_MATRIX_PATH = MATRIX_DIR / "homography_matrix.npy"
HOMOGRAPHY_META_PATH = MATRIX_DIR / "homography_meta.json"
YOLO_MODEL_PATH = PROJECT_ROOT / "yolo11n.pt"

CAMERA_INDEX = 1
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

SERIAL_PORT = "COM5"
SERIAL_BAUD = 9600

PICK_Z_MM = 70.0
APPROACH_CLEARANCE_MM = 30.0
LIFT_CLEARANCE_MM = 50.0

PLACE_X_MM = 200.0
PLACE_Y_MM = 200.0
PLACE_Z_MM = 70.0

DEFAULT_GRAB_PUMP_MS = 500
HOME_MOVE_MS = 1200
APPROACH_MOVE_MS = 1200
DESCEND_MOVE_MS = 900
LIFT_MOVE_MS = 1000
PLACE_MOVE_MS = 1200
MOVE_SETTLE_SEC = 0.20
GRAB_SETTLE_SEC = 0.70
RELEASE_SETTLE_SEC = 0.50

DEFAULT_TRIGGER_MODE = "manual"
AUTO_STABLE_FRAMES = 10
AUTO_STABLE_POSITION_JITTER_MM = 10.0
AUTO_COOLDOWN_SEC = 2.0

YOLO_ALLOWED_CLASSES = ("apple", "orange", "banana")
YOLO_CONFIDENCE = 0.60
YOLO_BBOX_FOOT_RATIO = 0.10

COLOR_LABEL = "red"
COLOR_MIN_RADIUS_PX = 20.0
COLOR_CONTACT_BACKOFF_PX = 6
COLOR_LOWER_RED_1 = (0, 120, 70)
COLOR_UPPER_RED_1 = (10, 255, 255)
COLOR_LOWER_RED_2 = (170, 120, 70)
COLOR_UPPER_RED_2 = (180, 255, 255)


def ensure_runtime_dirs() -> None:
    MATRIX_DIR.mkdir(parents=True, exist_ok=True)
